#!/bin/bash
# Subdomain db filtering
$ODOO_DB_FILTER=^%d_*

$ODOO_VERSION=10.0
$ODOO_COMMIT_HASH=60dbf05750532519c4cb73cd764ca9df37d7b229
$VERSION_DATE=2017-09-06

# Using default Dockerfile values for wkhtmltopdf
$WKHTMLTOPDF_DEB=""
$WKHTMLTOPDF_SHA=""
