#!/bin/bash
# Subdomain db filtering
$ODOO_DB_FILTER=^%d_*

$ODOO_VERSION=11.0
$ODOO_COMMIT_HASH=7fe7439c32692222c37209adf9bac97149651959
$VERSION_DATE=2017-10-24

# Using default Dockerfile values for wkhtmltopdf
$WKHTMLTOPDF_SRC=""
$WKHTMLTOPDF_SHA=""
